[package]
name = "car-park"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "car_park"
path = "src/lib.rs"

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"
